name: polkadart
description: Interfaces for interacting with Polkadot JsonRPC interface
version: 0.1.0
repository: https://github.com/rankanizer/polkadart

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  convert: ^3.1.1 # BSD-3-Clause
  http: ^0.13.5 # BSD-3-Clause
  pointycastle: ^3.6.2 # MIT
  web_socket_channel: ^2.3.0 # BSD-3-Clause
  polkadart_scale_codec: ^1.1.0-pre.2 # Apache 2.0
  substrate_metadata: ^1.1.0-pre.1 # Apache 2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
