name: polkadart
description: Interfaces for interacting with Polkadot JSON RPC interface
version: 0.4.7
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart
repository: https://github.com/leonardocustodio/polkadart

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  convert: ^3.1.1 # BSD-3-Clause
  http: ^1.2.2 # BSD-3-Clause
  pointycastle: ^3.6.2 # MIT
  web_socket_channel: ^2.3.0 # BSD-3-Clause
  polkadart_scale_codec: ^1.2.0 # Apache 2.0
  substrate_metadata: ^1.2.0 # Apache 2.0
  hashlib_codecs: ^2.2.0 # BSD-3-Clause
  polkadart_keyring: ^0.4.3
  ss58: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
