name: polkadart
description: Polkadart is a set of packages that provides a high-level interface for interacting with Polkadot, you can query storage, submit extrinsics, make RPC calls and much more. #polkadot #blockchain
version: 0.7.3
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  convert: ^3.1.1 # BSD-3-Clause
  http: ^1.4.0 # BSD-3-Clause
  web_socket_client: ^0.2.1 # MIT
  polkadart_scale_codec: ^1.6.0 # Apache 2.0
  substrate_metadata: ^1.6.0 # Apache 2.0
  ss58: ^1.3.0
  equatable: ^2.0.7
  json_serializable: 6.11.1
  json_annotation: 4.9.0

dev_dependencies:
  polkadart_keyring: ^0.7.1
  build_runner: 2.10.3
  lints: ^6.0.0
  test: ^1.26.3
