name: sr25519
description: A starting point for sr25519 library
version: 1.0.0
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/sr25519
repository: https://github.com/leonardocustodio/polkadart

environment:
  sdk: ^3.1.5

dependencies:
  collection: ^1.18.0
  convert: ^3.1.1
  cryptography: ^2.7.0
  merlin: ^1.0.3
  ristretto255: ^1.0.2
  substrate_bip39: ^0.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
