name: sr25519
description: A sr25519 cryptography library in pure Dart
version: 0.7.0
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/sr25519
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.18.0
  convert: ^3.1.1
  cryptography: ^2.7.0
  merlin: ^1.0.3
  ristretto255: ^1.0.2
  substrate_bip39: ^0.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
