name: polkadart_examples
description: A set of examples showing how to use Polkadart.
version: 1.0.0

environment:
  sdk: ">=3.0.1 <4.0.0"

# Add regular dependencies here.
dependencies:
  convert: any
  polkadart: any
  polkadart_cli: any
  polkadart_scale_codec: any
  polkadart_keyring: any
  ss58: any
  substrate_bip39: any
  substrate_metadata: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

polkadart:
  output_dir: lib/generated
  chains:
    polkadot: wss://rpc.polkadot.io