name: ss58
description: Provides encoding and decoding methods for parsing substrate SS58 addresses.
version: 1.3.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/ss58
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  equatable: 2.0.7 # MIT
  base_x: 2.0.1 # MIT
  convert: 3.1.2 # BSD-3-Clause
  cryptography: 2.9.0 # Apache-2.0
  json_annotation: 4.9.0 # BSD-3-Clause

dev_dependencies:
  lints: 6.0.0
  test: 1.28.0
  build_runner: 2.10.3
  json_serializable: 6.11.1

