name: ss58
description: ss58 description
version: 1.0.0
homepage: https://github.com/rankanizer/polkadart

# TODO: remove 'publish_to' when publishing 'ss58' on pub.dev.
# It's important to set 'publish_to' to 'none' for now to be able to get git packages 'ss58_codec' from polkadart repo.
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  equatable: ^2.0.5 # MIT
  # TODO: When publishing remove git reference by removing 'publish_to' in line 7
  # and change 'ss58_codec': to the pub.dev published version.
  ss58_codec:
    path: ../ss58_codec

dev_dependencies:
  convert: ^3.0.2 # BSD-3-Clause
  lints: ^2.0.0
  test: ^1.16.0
