name: ink_cli
description: ink_cli is a command line interface for ink! smart contracts. Generates code to interact with ink! smart contracts.
version: 0.0.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/ink_cli
repository: https://github.com/leonardocustodio/polkadart

# TODO: Remove after ink_abi 0.0.2 is published
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.0 # BSD-3-Clause
  console: ^4.1.0
  crypto: ^3.0.6 # MIT
  ink_abi:
    path: ../ink_abi
  polkadart: 0.4.7
  polkadart_keyring: ^0.4.3
  polkadart_scale_codec: ^1.2.0
  ss58: ^1.2.0
  substrate_metadata: ^1.3.0

dev_dependencies:
  path: ^1.8.3 # BSD-3-Clause
  yaml: ^3.1.1 # MIT
  polkadart: any
  lints: ^4.0.0
  test: ^1.24.0
