name: ink_cli
description: ink_cli is a command line interface for ink! smart contracts. Generates code to interact with ink! smart contracts.
version: 0.3.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/ink_cli
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.7.0 # BSD-3-Clause
  console: ^4.1.0
  crypto: ^3.0.7 # MIT
  path: ^1.8.3 # BSD-3-Clause
  ink_abi: ^0.3.1
  polkadart: ^0.7.2
  polkadart_keyring: ^0.7.1
  polkadart_scale_codec: ^1.6.0
  ss58: ^1.3.1
  substrate_metadata: ^1.6.0

dev_dependencies:
  yaml: ^3.1.1 # MIT
  lints: ^6.0.0
  test: ^1.28.0


