name: polkadart_cli
description: polkadart_cli is a dart library that generates Dart type code from frame metadata. Generated code relies on Polkadart library.
version: 0.7.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart_cli
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.7.0 # BSD-3-Clause
  code_builder: ^4.11.0 # BSD-3-Clause
  convert: ^3.1.1 # BSD-3-Clause
  dart_style: ^3.1.2 # BSD-3-Clause
  http: ^1.4.0 # BSD-3-Clause
  recase: ^4.1.0 # BSD-2-Clause
  path: ^1.8.3 # BSD-3-Clause
  yaml: ^3.1.1 # MIT
  polkadart: ^0.7.1 # Apache 2.0
  substrate_metadata: ^1.5.0 # Apache 2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
