name: polkadart_example
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  polkadart: ^0.2.0
  polkadart_cli: ^0.2.0
  polkadart_keyring: ^0.2.0
  polkadart_scale_codec: ^1.1.0
  ss58: ^1.1.0
  substrate_bip39: ^0.2.0
  substrate_metadata: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

polkadart:
  output_dir: lib/generated
  chains:
    polkadot: wss://rpc.polkadot.io