name: ink_abi
description: ink! abi encoder and decoder
version: 0.3.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/ink_abi
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  json_schema: ^5.2.2
  polkadart: ^0.7.2
  polkadart_scale_codec: ^1.6.0
  substrate_metadata: ^1.6.0
  utility: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.8.0
  lints: ^6.0.0
  test: ^1.28.0
