name: ink_abi
description: ink! abi encoder and decoder
version: 0.3.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/ink_abi
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  json_schema: ^5.2.2
  polkadart: ^0.7.2
  polkadart_scale_codec: ^1.6.0
  substrate_metadata: ^1.6.0
  utility: ^1.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
