name: substrate_metadata
description: Metadata types for Substrate runtimes
version: 1.1.0-pre.1
homepage: https://github.com/rankanizer/polkadart

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  equatable: ^2.0.5
  json_schema2: ^2.0.2+9 # MIT
  pointycastle: ^3.6.2 # BSD-3-Clause
  polkadart_scale_codec: ^1.1.0-pre.2 # Apache 2.0
  utility: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
