name: substrate_metadata
description: substrate_metadata description
version: 1.0.0
homepage: https://github.com/rankanizer/polkadart

# TODO: Remove this when polkadart_scale_codec is published
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached: ^1.2.2 # MIT
  cached_annotation: ^1.2.0 # MIT
  pointycastle: ^3.6.2 # BSD-3-Clause
  equatable: ^2.0.5 # MIT
  json_schema2: ^2.0.2+9 # MIT
  polkadart_scale_codec:
    path: ../polkadart_scale_codec
  weak_map: ^2.1.0 # BSD-2-Clause

dev_dependencies:
  build_runner: ^2.2.1 # BSD-3-Clause
  lints: ^2.0.0
  test: ^1.16.0
