name: substrate_metadata
description: Metadata types for Substrate runtimes
version: 1.2.3
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/substrate_metadata
repository: https://github.com/leonardocustodio/polkadart

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_schema: ^5.2.0 # MIT
  pointycastle: ^3.6.2 # BSD-3-Clause
  polkadart_scale_codec: ^1.2.0
  utility: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
