name: polkadart_keyring
description: Substrate Keyring.
version: 0.2.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart_keyring
repository: https://github.com/leonardocustodio/polkadart
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.1 <4.0.0"

# Add regular dependencies here.
dependencies:
  cryptography: ^2.5.0
  flutter_curve25519: ^0.1.2
  ss58: ^1.1.0
  substrate_bip39: ^0.2.0
  typed_data: ^1.3.1 # BSD-3-Clause
  ed25519_edwards: ^0.3.1
  convert: ^3.1.1
  sr25519: ^0.1.0
  merlin: ^1.0.3
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
