name: polkadart_keyring
description: Substrate Keyring.
version: 0.6.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart_keyring
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  pointycastle: ^3.6.2
  flutter_curve25519: ^0.1.2
  ss58: ^1.3.0
  substrate_bip39: ^0.6.0
  secp256k1_ecdsa: ^0.6.0
  typed_data: ^1.3.1 # BSD-3-Clause
  ed25519_edwards: ^0.3.1
  convert: ^3.1.1
  sr25519: ^0.6.0
  collection: ^1.18.0
  polkadart_scale_codec: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
