name: substrate_bip39
description: Converting BIP39 entropy to valid Substrate SecretKeys.
version: 0.1.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/substrate_bip39
repository: https://github.com/leonardocustodio/polkadart

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  bip39_mnemonic: ^3.0.6
  convert: ^3.1.1
  collection: ^1.17.2
  cryptography: ^2.5.0
  pointycastle: ^3.6.2
  polkadart_scale_codec: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
