name: frame_primitives
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/rankanizer/polkadart

publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  pointycastle: ^3.6.2 # MIT
  http: ^0.13.5 # BSD-3-Clause
  hex: ^0.2.0 # MIT
  polkadart_scale_codec: 
    path: ../polkadart_scale_codec

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
