name: polkadart_scale_codec
description: polkadart_scale_codec description
version: 1.0.0
homepage: https://github.com/rankanizer/polkadart

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  utility: ^1.0.3 # MIT
  convert: ^3.0.2 # BSD-3-Clause
  equatable: ^2.0.5 # MIT

dev_dependencies:
  build_runner: ^2.2.1 # BSD-3-Clause
  lints: ^2.0.0 # BSD-3-Clause
  test: ^1.16.0 # BSD-3-Clause
