name: polkadart_scale_codec
description: Implementation of the SCALE codec in Dart
version: 1.5.1
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart_scale_codec
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies: 
  convert: ^3.0.2 # BSD-3-Clause
  equatable: ^2.0.5 # MIT
  quiver: ^3.2.1 # Apache-2.0
  typed_data: ^1.3.1 # BSD-3-Clause
  substrate_metadata: ^1.5.0

dev_dependencies:
  lints: ^6.0.0 # BSD-3-Clause
  test: ^1.26.3 # BSD-3-Clause
