name: Tests
on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  markdown-link-check:
    name: Markdown link checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/workflows/mlc_config.json"

  lints:
    name: Check code lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check TOML Format
        uses: dprint/check@v2.0

  ss58_codec:
    name: Test ss58_codec
    needs: [lints, markdown-link-check]
    uses: rankanizer/polkadart/.github/workflows/reuseable_workflow.yml@feature/CI-CD
    with:
      working-directory: "./packages/ss58_codec"

  ss58:
    name: Test ss58
    needs: [lints, markdown-link-check]
    uses: rankanizer/polkadart/.github/workflows/reuseable_workflow.yml@feature/CI-CD
    with:
      working-directory: "./packages/ss58"

  polkadart_scale_codec:
    name: Test polkadart_scale_codec
    needs: [lints, markdown-link-check]
    uses: rankanizer/polkadart/.github/workflows/reuseable_workflow.yml@feature/CI-CD
    with:
      working-directory: "./packages/polkadart_scale_codec"

  polkadart:
    name: Test polkadart
    needs: [lints, markdown-link-check]
    uses: rankanizer/polkadart/.github/workflows/reuseable_workflow.yml@feature/CI-CD
    with:
      working-directory: "./polkadart"
