name: secp256k1_ecdsa
description: secp256k1_ecdsa helps to generate secp256k1 key pairs, sign/verify messages, compress/expand keys and recover public keys.
version: 0.6.2
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/secp256k1_ecdsa
repository: https://github.com/leonardocustodio/polkadart
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
